### ISSUE TITLE
Xignux - Calendario personalizado

### ISSUE THREAD

**Issue by rodmendoza07** [OvercastmxDemo/DevProjects#19]

**Comment by rodmendoza07** [comment]
@rramos9771 / @Rambx

¿Qué ha pasado?
¿Ya lo podemos cerrar?

**Comment by rramos9771** [comment]
Ya se dio la transferencia de conocimientos.
Ya no se debe nada de nuestra parte
ya se podría cerrar.

**Comment by rramos9771** [comment]
Se mando correo para informar de cierre del proceso de desarrollo

**Comment by rodmendoza07** [comment]
@rramos9771 / @Rambx 

Por favor adjuntar imagen del correo que se mandó para el cierre de proyecto

**Comment by rramos9771** [comment]
@rodmendoza07 
![image](https://user-images.githubusercontent.com/96545484/199271846-827d5dc9-365b-450f-9f3c-e8dc31afb40a.png)

**Comment by rodmendoza07** [comment]
@Rambx / @rramos9771 

¿Ya lo podemos cerrar?

**Comment by rodmendoza07** [comment]
@Rambx / @rramos9771 

Derivado que ya termino el periodo de garantía se cierra el proyecto
