### ISSUE TITLE
Niubiz - Reserva tu lugar

### ISSUE THREAD

**Issue by rodmendoza07** [OvercastmxDemo/DevProjects#31]

**Comment by rodmendoza07** [comment]
@LuisAlbertoOvercast / @Rambx 

![Image](https://user-images.githubusercontent.com/18431533/196164775-7eb15ebb-e0ad-423c-8bd4-bfe91994dfce.png)

**Comment by rodmendoza07** [comment]
@Rambx / @LuisAlbertoOvercast 

Dado que el cliente no contesto desde el 11/10 se pasa de soporte a terminado

**Comment by LuisAlbertoOvercast** [comment]
se han terminado los cambios que presento el cliente, en espera de su validación 



![Image](https://user-images.githubusercontent.com/101677829/199763920-ae0edd79-05e7-4406-97cf-32443262d70b.png)
