### ISSUE TITLE
Xignux - Reserva tu lugar

### ISSUE THREAD

**Issue by rodmendoza07** [OvercastmxDemo/DevProjects#33]

**Comment by rodmendoza07** [comment]
@rramos9771 / @Rambx 

![Image](https://user-images.githubusercontent.com/18431533/196165703-d8b027fd-1674-48b2-abb1-1458c4d65357.png)

**Comment by rramos9771** [comment]
Se mando correo para informar de cierre del proceso de desarrollo

**Comment by rramos9771** [comment]
Hola @rodmendoza07 y @Rambx  a partir del 28/10/2022 inicia la fase de soporte
Se envió correo de notificación al cliente el 31/10/2022.

![image](https://user-images.githubusercontent.com/96545484/201443229-3c037daf-49ff-4e80-a902-f566c791dfda.png)

**Comment by rodmendoza07** [comment]
@Rambx / @rramos9771 

Se termina el periodo de garantía por tal motivo se Cierra el proyecto
