### ISSUE TITLE
Posadas - Formularios

### ISSUE THREAD

**Issue by rodmendoza07** [OvercastmxDemo/DevProjects#34]

**Comment by rodmendoza07** [comment]
@rramos9771 / @Rambx 

![Image](https://user-images.githubusercontent.com/18431533/196166331-73beb624-5912-4c53-919e-e87a7cd713b6.png)
![Image](https://user-images.githubusercontent.com/18431533/196166398-edb360ba-d7a7-46d9-8ca4-abf08b9ef0d2.png)
![Image](https://user-images.githubusercontent.com/18431533/196166464-33bc43a2-677a-4dca-b31f-25dfe5fa2322.png)

**Comment by rodmendoza07** [comment]
@rramos9771 / @Rambx 

Qué ha pasado?
Ya lo podemos cerrar?

**Comment by Rambx** [comment]
@rramos9771  / @rodmendoza07 
Hola les comparto el correo que mandó Mario como apoyo en seguimiento a la cuenta. 



![Image](https://user-images.githubusercontent.com/115195515/197103514-20becc49-4614-4008-97d4-f4cb2da753b5.png)

**Comment by rodmendoza07** [comment]
Tiene disponible el 40%

![Image](https://user-images.githubusercontent.com/18431533/198721273-edebc905-2653-4073-91b9-23c46c7d8e1b.png)

**Comment by rramos9771** [comment]
@rodmendoza07  y @Rambx 
El día de hoy se mandó correo a javier y cralos para notificar el inicio de la transferencia de conocimientos y proceder a la fase de soporte.

![image](https://user-images.githubusercontent.com/96545484/201443004-c5c29528-68a9-400e-b4f8-91e867438e58.png)

**Comment by rodmendoza07** [comment]
@Rambx / @Rambx 

¿Cómo vamos, ya lo podemos cerrar?

**Comment by rodmendoza07** [comment]
@rramos9771 / @Rambx 

El viernes 2/12/2022 se tuvo sesión con el cliente. ¿Cuál es el estatus?

**Comment by Rambx** [comment]
@rodmendoza07  @rramos9771 
 Comparto el correo que envié a Javier Solís



![Image](https://user-images.githubusercontent.com/115195515/205721713-fb7909ef-6fca-4b91-9af7-982c5ad645b8.png)

**Comment by rodmendoza07** [comment]
Derivado de este último correo, el proyecto comienza su periodo de garantía de 30 días 

Inicio de garantía 14/12/2022
Termino 14/01/2023



![Image](https://user-images.githubusercontent.com/18431533/207782282-3f39e609-fd42-461d-b15f-8e68b5dea7b3.png)

**Comment by rramos9771** [comment]
@rodmendoza07 @Rambx El día 16/01/2023 se solucionó el issue sobre la opción para edición del formulario de RFC.
Se requiere avisarle al cliente que regresen los nombres que tenían las listas de SharePoint anteriormente por que la app va a mandar error y el cambio de estas en la app requiere mucho tiempo.

**Comment by rodmendoza07** [comment]
Se mueve a terminado ya que la garantía se termino
