### ISSUE TITLE
Santander - Mentoring Power Platform

### ISSUE THREAD

**Issue by rodmendoza07** [OvercastmxDemo/DevProjects#37]

**Comment by rodmendoza07** [comment]
@lalonso-dac / @Rambx 

![Image](https://user-images.githubusercontent.com/18431533/196168114-b03a3809-cf5c-4a23-bb20-e2074d763dc4.png)
![Image](https://user-images.githubusercontent.com/18431533/196168192-7871eec6-0e20-4060-8035-ef19db8e0b0a.png)
![Image](https://user-images.githubusercontent.com/18431533/196168263-ab897014-e4ba-4d40-aa32-c51ed03dbe7a.png)
![Image](https://user-images.githubusercontent.com/18431533/196168384-7b997dba-8894-43dd-92d7-034a47693b72.png)

**Comment by rodmendoza07** [comment]
@lalonso-dac / @Rambx 

Que ha pasado?
En que sesión va?

Cuál es la fecha de termino?

**Comment by Rambx** [comment]
C.C. @lalonso-dac / @rodmendoza07 

Nos encontramos en la sesión número 12 de un total de 20... recordando que las primeras 3 sesiones no se entregaron y se estarán realizando al final.

**Comment by lalonso-dac** [comment]
El día Lunes 17 de Octubre se realizó la sesión en la que se dió una introducción a PowerBi  usando material Didactico explicando como funciona powerBi de forma general

**Comment by lalonso-dac** [comment]
El día Miercoles 19 de Octubre se realizó la sesión en la que se habló de como hacer transformación de datos usando como base un archivo excel, se habló de las distintas fuentes de datos con las que cuenta Power bi para obtener información, y hablamos un poco de Dax

**Comment by lalonso-dac** [comment]
El día Viernes 21de Octubre se continuó hablando de dax, y como crear columnas y medidas, tambien sus diferencias, crear columnas condicionales, crear vistas y como agregar, customizar, y dar diseño a los dashboard, se creó un tablero con un reporte de filtrado por Pais, continente, productos, tipos de producto, Ingresos, gastos, y finalizando haciendo la carga en Power Bi service, accediendo por un Qr desde nuestro dispositivo movil al dashboard

**Comment by lalonso-dac** [comment]
El día Lunes 24 de Octubre se comenzó el tema de Ai builder, probamos la funcionalidad para entrenar un modelo usando la opción de entrenar modelo customizado para extracción de información de formularios, entrenamos el modelo con Facturas, y otro modelo con estados de cuenta de Santander, finalizando con una prueba desde Power Automate, leyendo correos e identificando la información de los correos recibidos

**Comment by lalonso-dac** [comment]
El día Miercoles 1926 de Octubre se  probaron las formas de extraer datos desde modelos haciendo uso de imagenes, y probando componentes desde power Apps, los modelos se usaron para validar la información de los formularios finalizando las pruebas con una demo desde power Apps y power Automate

**Comment by lalonso-dac** [comment]
El día Viernes 21 de Octubre se crearon modelos de "reconocimiento de texto en imagenes", "reconocimento de texto en tikets", "extracción de texto en identificaciones", se creó una demo desde Power Apps, usando los componentes y conectando modelos, mostrando la data en tables, labels, en power Apps

**Comment by lalonso-dac** [comment]
## nuevas sesiónes Agendadas


el día lunes  24/10/2022 se compartieron nuevas sesiónes 

![Image](https://user-images.githubusercontent.com/88047449/198675122-c160502b-a227-455d-95cb-ca0b5ca5c770.png)


A continuación se adjuntan los links para el acceso a las sesiones

[Ligas de acceso para sesiones Power Apps Santander.docx](https://github.com/OvercastmxDemo/DevProjects/files/9889813/Ligas.de.acceso.para.sesiones.Power.Apps.Santander.docx)

**Comment by lalonso-dac** [comment]
el día 31/10/2022 se realizó una mentoria en la que entrenamos un modelo de reconocimiento de imagenes con AI Builder, seguido de ello realizamos pruebas para verificar el reconocimiento de imagenes y probar su exactitud

**Comment by lalonso-dac** [comment]
Fechas de sesiones restantes de Power Apps

1.- 04/11/2022
2.- 07/11/2022
3.- 09/11/2022
4.- 11/11/2022

**Comment by lalonso-dac** [comment]
@#la siesión del dia 04/11/2022  se va a tener acceso con la siguiente URL

@Rambx 
[link a la sesión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjdmYTViMTYtNTQyMi00NTFmLWE0YjYtOGQ4YjgxOGU4Mjg5%40thread.v2/0?context=%7b%22Tid%22%3a%2235595a02-4d6d-44ac-99e1-f9ab4cd872db%22%2c%22Oid%22%3a%220ae3bfde-3cec-4526-98d1-f99f82521f1f%22%7d)

**Comment by lalonso-dac** [comment]
el día 07/11/2022 se realizó sesión en la que 
-se creó un modelo con la herramienta **Lobe.ai**. 
-se creó un modelo etiquetando imagenes de una persona tomando agua, para detectar este patron, 
-se explicó de forma general el funcionamiento de Yammer, haciendo publicaciones, entre otras funcionalidades
-se creó un flujo para obtener el texto de las publicaciones y calcular con **Yammer** si la publicación es **positiva** o **negativa**
-se crearon registros en **Excel** con los datos obentidos de las publicaciones,
-se creó un tablero en **Power Bi** para ver la información obtenida de las publicaciones en **Yammer**

**Comment by lalonso-dac** [comment]
El día 14/11/2022 se realizó la ultima sesión de mentoria, en la que se resolvieron dudas cone apoyo de Luis Alberto tzun en Virtual Agents, power automate y sharepoint, dando por finalizadas las sesiones de mentorias

**Comment by Rambx** [comment]
@rodmendoza07 @lalonso-dac 
Comparto el correo que envié al cliente 



![Image](https://user-images.githubusercontent.com/115195515/201725740-7fc2cd94-bab3-4a7d-8791-a02569f1b47c.png)

**Comment by rodmendoza07** [comment]
@Rambx 

Ya se puede cerrar el proyecto??

**Comment by rodmendoza07** [comment]
@Rambx 

Se cierra el proyecto ya que el cobro es un tema comercial, el curso fue completado de manera exitosa

**Comment by rodmendoza07** [comment]
Proyecto realizado por Leonardo
