### ISSUE TITLE
Banco de la Atlantida - Solicitud de Viáticos

### ISSUE THREAD

**Issue by rodmendoza07** [OvercastmxDemo/DevProjects#4]

**Comment by rodmendoza07** [comment]
@doriansmmm / @Rambx 



![Image](https://user-images.githubusercontent.com/18431533/196151669-df0d0132-bb2b-4cbf-a748-64fc458aba1c.png)
![Image](https://user-images.githubusercontent.com/18431533/196151728-224997d1-2c6d-4388-baf9-b0d3e0276a51.png)

**Comment by Rambx** [comment]
Comentarios de Omar del día 17/10 

De: Luis Omar Ramírez Ortíz <ramirez.omar@overcastmx.com> 
Enviado el: lunes, 17 de octubre de 2022 04:04 p. m.
Para: Erika Nohemí Aguilar Carbajal <eaguilar@overcastmx.com>; Claudia Marcela Nunez Galvez <cmnunez@bancatlan.hn>; Ivan Zuniga Orban <izuniga@bancatlan.hn>; Hector David Gallegos Aviles <hgallegos@bancatlan.hn>; Elsy Pamela Montalvan <epmontalvan@bancatlan.hn>; Jose Abrahan Guillen Baquedano <jaguillen@bancatlan.hn>
CC: Brenda Cruz Méndez <bcruz@overcastmx.com>; Rodrigo Mendoza <rodrigo.mendoza@overcastmx.com>; Ruben Abraham Mendoza Betancourt <rmendoza@overcastmx.com>; Obed Gael Pérez Prieto <perez.obed@overcastmx.com>; Gael Perez <gael.perez@overcastmx.com>; Dorian Steven Mendoza Martínez <dmendoza@overcastmx.com>
Asunto: RE: Banco Atlántida | App viáticos
Importancia: Alta

Buen día [@Ivan Zuniga Orban](mailto:izuniga@bancatlan.hn) y equipo

Sumando al correo anterior me gustaría hacer énfasis en las fechas de entrega del proyecto, ya que como ustedes saben, tenemos un compromiso ante Microsoft que ya se cumplió y hemos retrasado por diversas razones, es por eso que pido de su apoyo para ayudarnos a liberar la aplicación como lo menciona [@Erika Nohemí Aguilar Carbajal](mailto:eaguilar@overcastmx.com) y de esa forma cerrar administrativamente ante Microsoft de acuerdo a las fechas que teníamos comprometidas.

De antemano muchas gracias por su apoyo y atención, quedo pendiente de su valiosa respuesta.

Saludos.

**Comment by rodmendoza07** [comment]
@doriansmmm / @Rambx 

¿Ya podemos cerrar este proyecto?

**Comment by doriansmmm** [comment]
Hola @Rambx @rodmendoza07 


![Image](https://user-images.githubusercontent.com/100003393/206038146-09200a5b-b608-497a-ab94-10185277f811.png)

**Comment by rodmendoza07** [comment]
Derivado del correo anterior, se pasa de desarrollo a soporte

**Comment by rodmendoza07** [comment]
Se mueve a terminado. La garantía ya termino
