### ISSUE TITLE
ITESM - Flujo de procesos con documentos / Gestor documental

### ISSUE THREAD

**Issue by rodmendoza07** [OvercastmxDemo/DevProjects#46]

**Comment by rodmendoza07** [comment]
@Rambx 

![Image](https://user-images.githubusercontent.com/18431533/196171373-3fef466b-fd11-4c54-ad85-7c9f1cde6307.png)

**Comment by Rambx** [comment]
@rodmendoza07 

De la reunión de Lunes de Sync Comercial, Luis Omar comentó que el cliente ya no responde , damos por cerrada la propuesta.
