### ISSUE TITLE
ICA FLUOR - Company Comunicator

### ISSUE THREAD

**Issue by rodmendoza07** [OvercastmxDemo/DevProjects#9]

**Comment by rodmendoza07** [comment]
@Rambx 

¿ya lo podemos cerrar?

**Comment by rodmendoza07** [comment]
Derivado que no hay respuesta del cliente. El proyecto se pone en pausa



![Image](https://user-images.githubusercontent.com/18431533/205703378-5c6c489d-172f-4a91-a4a6-16c8bee5c4b3.png)

**Comment by doriansmmm** [comment]
El día de hoy 19/12/2022 se configuró el PAL de overcast, se entregó la documentación necesaria para enviar comunicados, agregar nuevos autores y se realizó el envío masivo



![Image](https://user-images.githubusercontent.com/100003393/208496954-c0241742-65ad-4c50-97fd-e082e4091648.png)



![Image](https://user-images.githubusercontent.com/100003393/208496964-cf988a3c-cd12-4fc8-b158-530327df5681.png)



![Image](https://user-images.githubusercontent.com/100003393/208497052-9eebccda-fe7c-4838-9e9e-71a4a68ba204.png)

**Comment by doriansmmm** [comment]
La fase de garantía empieza el día 19/12/2022 y termina el 03/01/2023 



![Image](https://user-images.githubusercontent.com/100003393/208501572-c7f2198a-f2b9-4e9e-9af6-2a165052e9ec.png)

**Comment by rodmendoza07** [comment]
@Rambx / @doriansmmm 

Se ha terminado el tiempo de garantía de este proyecto. Por favor notificar al cliente que ya no está en garantía.

Al terminar esta garantía se cierra el proyecto.
